# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/S4Projet/joystick/joystick.srcs/sources_1/bd/joystick_pmod/ip/joystick_pmod_rst_ps7_0_50M_0/joystick_pmod_rst_ps7_0_50M_0.xci
# IP: The module: 'joystick_pmod_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/S4Projet/joystick/joystick.gen/sources_1/bd/joystick_pmod/ip/joystick_pmod_rst_ps7_0_50M_0/joystick_pmod_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'joystick_pmod_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/S4Projet/joystick/joystick.gen/sources_1/bd/joystick_pmod/ip/joystick_pmod_rst_ps7_0_50M_0/joystick_pmod_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'joystick_pmod_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/S4Projet/joystick/joystick.gen/sources_1/bd/joystick_pmod/ip/joystick_pmod_rst_ps7_0_50M_0/joystick_pmod_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'joystick_pmod_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/S4Projet/joystick/joystick.srcs/sources_1/bd/joystick_pmod/ip/joystick_pmod_rst_ps7_0_50M_0/joystick_pmod_rst_ps7_0_50M_0.xci
# IP: The module: 'joystick_pmod_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/S4Projet/joystick/joystick.gen/sources_1/bd/joystick_pmod/ip/joystick_pmod_rst_ps7_0_50M_0/joystick_pmod_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'joystick_pmod_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/S4Projet/joystick/joystick.gen/sources_1/bd/joystick_pmod/ip/joystick_pmod_rst_ps7_0_50M_0/joystick_pmod_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'joystick_pmod_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/S4Projet/joystick/joystick.gen/sources_1/bd/joystick_pmod/ip/joystick_pmod_rst_ps7_0_50M_0/joystick_pmod_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'joystick_pmod_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
