# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/common/Zybo-Z7-Master.xdc

# Block Designs: bd/joystick_pmod/joystick_pmod.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joystick_pmod || ORIG_REF_NAME==joystick_pmod} -quiet] -quiet

# IP: bd/joystick_pmod/ip/joystick_pmod_processing_system7_0_0/joystick_pmod_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joystick_pmod_processing_system7_0_0 || ORIG_REF_NAME==joystick_pmod_processing_system7_0_0} -quiet] -quiet

# IP: bd/joystick_pmod/ip/joystick_pmod_xbar_0/joystick_pmod_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joystick_pmod_xbar_0 || ORIG_REF_NAME==joystick_pmod_xbar_0} -quiet] -quiet

# IP: bd/joystick_pmod/ip/joystick_pmod_auto_pc_0/joystick_pmod_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joystick_pmod_auto_pc_0 || ORIG_REF_NAME==joystick_pmod_auto_pc_0} -quiet] -quiet

# IP: bd/joystick_pmod/ip/joystick_pmod_axi_interconnect_0_0/joystick_pmod_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joystick_pmod_axi_interconnect_0_0 || ORIG_REF_NAME==joystick_pmod_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/joystick_pmod/ip/joystick_pmod_axi_gpio_0_0/joystick_pmod_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joystick_pmod_axi_gpio_0_0 || ORIG_REF_NAME==joystick_pmod_axi_gpio_0_0} -quiet] -quiet

# IP: bd/joystick_pmod/ip/joystick_pmod_PmodJSTK2_0_0/joystick_pmod_PmodJSTK2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joystick_pmod_PmodJSTK2_0_0 || ORIG_REF_NAME==joystick_pmod_PmodJSTK2_0_0} -quiet] -quiet

# IP: bd/joystick_pmod/ip/joystick_pmod_rst_ps7_0_50M_0/joystick_pmod_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joystick_pmod_rst_ps7_0_50M_0 || ORIG_REF_NAME==joystick_pmod_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/S4Projet/joystick/joystick.gen/sources_1/bd/joystick_pmod/joystick_pmod_ooc.xdc
